export type Course = {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  level: string;
  audience: string;
  outcome: string;
  parts: readonly string[];
  badge?: string;
  relatedSkills?: readonly string[];
  highlights?: readonly string[];
};

export const COURSES: Course[] = [
  {
    slug: "landing-page",
    title: "랜딩페이지 만들기",
    tagline: "15가지 사례로 배우는, 전환율 높은 한 페이지 만들기",
    description:
      "제품 출시, 강좌 모집, 앱 다운로드, 이벤트 프로모션, 포트폴리오까지 — 5가지 유형 15개 실전 사례를 Claude Code로 만듭니다. 준비물 정리부터 CTA 최적화, Vercel 배포, 전환 추적까지 8강으로 끝냅니다.",
    level: "완전 초보",
    audience: "상품·서비스·강좌·이벤트를 알리는 한 페이지가 당장 필요한 사람",
    outcome: "전환율 높은 랜딩페이지 1개 + 15가지 사례 템플릿",
    parts: ["1부 · 구조와 준비", "2부 · 유형별 실전", "3부 · 최적화와 공개"],
    badge: "Windows · macOS",
    highlights: [
      "랜딩페이지 vs 홈페이지 — 목적과 구조의 차이",
      "전환율을 결정하는 7가지 블록 공식",
      "제품·SaaS·핸드메이드·구독 서비스 출시 사례",
      "강좌·워크숍·부트캠프 수강생 모집 사례",
      "앱 다운로드·사전예약·크라우드펀딩 사례",
      "세미나·할인 프로모션·뉴스레터 구독 사례",
      "프리랜서·컨설턴트·작가 개인 브랜딩 사례",
      "CTA 색상·문구·위치 최적화",
      "Vercel 배포 + 도메인 연결 + 전환 추적(GA4)",
      "A/B 테스트로 헤드라인·CTA 비교",
    ],
    relatedSkills: [
      "install-and-first-run",
      "prompt-writing",
      "images-and-files",
      "git-workflow",
      "one-slice-loop",
      "error-debugging",
    ],
  },
  {
    slug: "homepage",
    title: "홈페이지 만들기",
    tagline: "가게·개인·포트폴리오 홈페이지를 11일 만에 내 주소로",
    description:
      "완전 초보자를 위한 과정입니다. 프레임워크 없이 HTML 한 장부터 시작해 사진, 지도, 문의 폼이 있는 홈페이지를 만들고 내 도메인으로 공개합니다. 모든 설치·터미널 단계는 Windows와 macOS를 나란히 안내합니다.",
    level: "완전 초보",
    audience: "터미널을 한 번도 열어본 적 없는 사람",
    outcome: "내 도메인으로 공개된 여러 페이지짜리 홈페이지",
    parts: ["1부 · 준비", "2부 · 만들기", "3부 · 공개"],
    badge: "Windows · macOS",
    highlights: [
      "Claude Code 설치부터 첫 대화까지 5분 세팅",
      "HTML·CSS 없이 AI 대화만으로 페이지 구성",
      "사진 갤러리, 카카오 지도, 문의 폼 추가",
      "GitHub 연결 → Vercel 무료 배포",
      "가비아 도메인 구매 → Vercel 연결 (DNS 설정 상세)",
      "반응형 — 폰·태블릿·PC 자동 대응",
      "구글 서치 콘솔·네이버 서치 어드바이저 검색 등록",
      "CLAUDE.md 규칙 파일로 AI 품질 관리",
    ],
    relatedSkills: [
      "install-and-first-run",
      "desktop-app-vs-cli",
      "permissions-and-safety",
      "one-slice-loop",
      "prompt-writing",
      "git-workflow",
      "images-and-files",
      "error-debugging",
    ],
  },
  {
    slug: "homepage-cli",
    title: "홈페이지 만들기 — 고급",
    tagline: "지도 API·Analytics·MCP·어드민·SEO·대시보드까지",
    description:
      "기본 홈페이지 과정을 마친 뒤 한 단계 더. 네이버·카카오 지도 API, Vercel Analytics, Chrome Extension + Aside Browser(Computer Use), MCP 확장, 도메인 고급 설정, Pocketbase/Supabase 어드민, 카카오 OAuth, SEO 고급(JSON-LD·Core Web Vitals), 구글·네이버 서치 어드바이저, 통합 관리 대시보드까지 단계별로 다룹니다.",
    level: "입문+",
    audience: "홈페이지 과정을 마쳤고 더 많은 기능을 원하는 사람",
    outcome: "지도 API, 방문자 통계, MCP 자동화, 어드민 대시보드, 카카오 로그인, SEO 고급, 검색 등록, 통합 관리 대시보드",
    parts: ["고급 · 도구 활용", "고급 · 어드민 & 인증", "고급 · SEO & 대시보드"],
    badge: "고급 · Windows · macOS",
    highlights: [
      "네이버·카카오 지도 API 연동 (마커·인포윈도우)",
      "Vercel Analytics로 방문자·페이지뷰 추적",
      "Chrome Extension 사이드 패널에서 Claude 사용",
      "Aside Browser + Computer Use 자동 조작",
      "MCP 서버로 Playwright·검색·파일 시스템 확장",
      "Pocketbase / Supabase 어드민 대시보드 구축",
      "카카오 OAuth 소셜 로그인",
      "JSON-LD 구조화 데이터, Core Web Vitals 최적화",
      "구글 서치 콘솔 · 네이버 서치 어드바이저 연동",
    ],
    relatedSkills: [
      "mcp-and-tools",
      "desktop-app-vs-cli",
      "plan-mode-and-context",
      "rules-file-deep-dive",
      "git-workflow",
      "error-debugging",
    ],
  },
  {
    slug: "naver-blog",
    title: "네이버 블로그 생성 자동화",
    tagline: "키워드 하나로 리서치·초안·이미지·에디터 입력까지, 주 3편",
    description:
      "네이버 키워드 도구로 주제를 고르고, Claude Code가 출처가 붙은 리서치로 초안을 쓰고, 이미지와 제목·태그를 준비한 뒤, 브라우저 자동화로 스마트에디터에 원고를 채워 임시저장까지 합니다. 발행 버튼은 사람이 누릅니다. 네이버 검색 노출 원리와 저품질을 피하는 경계를 함께 다룹니다.",
    level: "입문+",
    audience: "Claude Code를 설치해본 사람. 네이버 블로그를 꾸준히 쓰고 싶지만 매번 막히는 사람",
    outcome: "30개 키워드 캘린더, 주제만 넣으면 에디터에 원고가 채워지는 파이프라인, 첫 글 3편",
    parts: ["1부 · 준비", "2부 · 파이프라인 만들기", "3부 · 자동화와 운영"],
    badge: "Windows · macOS",
    highlights: [
      "네이버 키워드 도구로 검색량·경쟁도 분석",
      "30개 주제 키워드 캘린더 한 번에 생성",
      "Claude Code 리서치 → 출처 달린 초안 자동 작성",
      "OG 이미지·본문 삽입 이미지 자동 생성",
      "스마트에디터에 브라우저 자동화로 원고 채우기",
      "발행 전 사람이 검토하는 안전 장치",
      "네이버 C-Rank·D.I.A. 알고리즘 이해",
      "저품질 블로그를 피하는 경계선과 규칙",
    ],
    relatedSkills: [
      "prompt-writing",
      "plan-mode-and-context",
      "mcp-and-tools",
      "skill-system",
      "images-and-files",
      "rules-file-deep-dive",
    ],
  },
  {
    slug: "shorts",
    title: "쇼츠 자동화",
    tagline: "건축물 이름 하나로 대본·영상·더빙(Typecast·ElevenLabs)·합성까지, 한 달 4편",
    description:
      "Claude Code가 레퍼런스 채널을 분석해 대본과 비주얼 프롬프트를 뽑고, Google Flow로 클립을 만들고, Typecast(한국어 최적) 또는 ElevenLabs로 더빙하고, ffmpeg로 9:16 쇼츠를 조립합니다. 구글 콘솔(YouTube Data API)로 자동 업로드까지 구현하며, 마지막엔 전체 파이프라인을 스킬 하나로 저장해 원클릭 실행합니다.",
    level: "입문+",
    audience: "Claude Code를 설치해본 사람 (홈페이지 만들기 3강 또는 웹 서비스 만들기 3강까지)",
    outcome: "주제만 넣으면 업로드까지 돌아가는 쇼츠 자동화 파이프라인과 첫 영상 1편",
    parts: ["1부 · 준비", "2부 · 파이프라인 만들기", "3부 · 자동화와 운영"],
    badge: "Windows · macOS",
    highlights: [
      "레퍼런스 채널 분석 → 구조·후크 패턴 추출",
      "22컷 대본 + 비주얼 프롬프트 자동 생성",
      "Google Flow / Veo로 9:16 AI 클립 생성",
      "Typecast(한국어) · ElevenLabs(다국어) 더빙 비교·선택",
      "ffmpeg 한 줄로 클립 + 음성 + BGM + 자막 합성",
      "호흡 맞추기 — 대본·속도·무음 패딩 3단계",
      "구글 클라우드 콘솔(YouTube Data API v3) 자동 업로드 구축",
      "스킬 파일로 전체 파이프라인 원클릭 저장",
      "주 1편 자동 생산 운영 루틴",
    ],
    relatedSkills: [
      "prompt-writing",
      "plan-mode-and-context",
      "skill-system",
      "images-and-files",
      "git-workflow",
      "error-debugging",
    ],
  },
  {
    slug: "sns",
    title: "SNS 배포 자동화",
    tagline: "글 하나를 다섯 채널에 맞게 변환하고 예약 발행",
    description:
      "블로그 글이나 영상 하나를 X·스레드·인스타그램·링크드인·카카오 채널·Facebook 페이지 형식으로 자동 변환하고, 이미지 카드를 만들고, 스케줄러 API로 예약 발행합니다. Facebook Graph API와 Meta Threads API 직접 연동도 다루고, 주간 성과를 모아 잘 된 후크 패턴을 규칙 파일에 되먹입니다.",
    level: "입문+",
    audience: "Claude Code를 설치해본 사람. 콘텐츠는 있는데 채널마다 올리는 게 일인 사람",
    outcome: "채널별 변환 규칙, 이미지 카드 템플릿, '이 글 배포해줘' 한 줄로 도는 파이프라인",
    parts: ["1부 · 준비", "2부 · 파이프라인 만들기", "3부 · 자동화와 운영"],
    badge: "Windows · macOS",
    highlights: [
      "원본 콘텐츠 → 7개 채널 형식 자동 변환",
      "X · 스레드 · 인스타 · 링크드인 · 카카오채널 · Facebook 페이지·개인",
      "채널별 이미지 카드 자동 생성 (비율·크기 맞춤)",
      "Buffer·Publer 등 스케줄러 API 예약 발행",
      "Facebook Graph API로 페이지 직접 자동 포스팅",
      "Meta Threads API로 스레드 직접 발행",
      "Facebook 개인 프로필은 Aside 브라우저로 반자동",
      "주간 성과 리포트 → 잘 된 후크 패턴 분석",
      "규칙 파일에 성과 피드백 자동 반영",
      "콘텐츠 캘린더 + 주간 배포 루틴",
    ],
    relatedSkills: [
      "prompt-writing",
      "skill-system",
      "rules-file-deep-dive",
      "mcp-and-tools",
      "images-and-files",
      "plan-mode-and-context",
    ],
  },
  {
    slug: "aside",
    title: "Claude Aside 완전 가이드",
    tagline: "Browser·Computer Use·MCP·스킬로 SEO·SNS·블로그·영상을 자동화",
    description:
      "Claude Code 데스크탑 앱의 Aside Browser, Computer Use, MCP 서버, Chrome Extension을 완전히 익히고 실전 자동화에 적용합니다. 서치 콘솔 자동 등록(SEO), 인스타·X·카카오채널 자동 배포(SNS), 네이버·티스토리 자동 포스팅(블로그), YouTube·쇼츠·릴스·틱톡 영상 파이프라인, HyperFrames(/hyperframes)로 모션그래픽, Remotion으로 데이터 기반 반복 렌더까지. 마지막에는 반복 작업을 스킬(SKILL.md)로 저장해 한 줄 호출로 실행합니다.",
    level: "입문+",
    audience: "홈페이지·서비스를 만든 뒤 운영을 자동화하고 싶은 사람",
    outcome: "Computer Use 자동화, SEO 루틴, SNS 5채널 배포, 블로그 원클릭 발행, 유튜브·쇼츠 파이프라인, HyperFrames 모션그래픽, Remotion 데이터 영상, 스킬 파일로 원클릭 자동화",
    parts: ["1부 · Aside 도구 기초", "2부 · SEO 자동화", "3부 · SNS 자동 배포", "4부 · 블로그 자동화", "5부 · 영상 자동화"],
    badge: "Windows · macOS",
    highlights: [
      "Aside Browser — 앱 안의 브라우저로 외부 사이트 탐색",
      "Computer Use — Claude가 클릭·입력·스크롤 직접 조작",
      "MCP 서버 연결 — Playwright·검색·파일 시스템 확장",
      "Chrome Extension 사이드 패널 활용",
      "구글 서치 콘솔·네이버 서치 어드바이저 자동 등록(SEO)",
      "Core Web Vitals 분석 및 최적화",
      "인스타·X·카카오 등 5채널 SNS 자동 배포",
      "네이버·티스토리 블로그 자동 포스팅",
      "YouTube Studio 업로드·썸네일·예약 자동화",
      "HyperFrames 모션그래픽, Remotion 데이터 영상 렌더",
      "SKILL.md로 전체 파이프라인 원클릭 실행",
    ],
    relatedSkills: [
      "desktop-app-vs-cli",
      "mcp-and-tools",
      "skill-system",
      "prompt-writing",
      "rules-file-deep-dive",
      "images-and-files",
      "plan-mode-and-context",
      "error-debugging",
    ],
  },
  {
    slug: "vibe-coding",
    title: "웹 서비스 만들기 20강",
    tagline: "코딩을 몰라도, 20일이면 내 서비스가 나옵니다",
    description:
      "아이디어 정리부터 화면, 데이터 저장, 로그인, 배포, 앱 출시까지. Next.js와 Supabase로 로그인과 데이터가 있는 진짜 서비스를 만듭니다.",
    level: "입문",
    audience: "홈페이지를 넘어 '서비스'를 만들고 싶은 사람",
    outcome: "로그인·데이터 저장이 되는 웹 서비스와 폰에 설치되는 PWA",
    parts: ["1부 · 준비", "2부 · 기획과 프롬프트", "3부 · 만들기", "4부 · 세상에 내놓기"],
    highlights: [
      "아이디어 → PLAN.md 기획 문서 작성",
      "Next.js 프로젝트 생성과 폴더 구조 이해",
      "AI 대화로 UI 컴포넌트·페이지 자동 생성",
      "Supabase 데이터베이스 테이블 설계·연동",
      "이메일·소셜 로그인 (Supabase Auth)",
      "데이터 CRUD — 등록·조회·수정·삭제",
      "Vercel 배포와 환경변수 관리",
      "PWA 설정 — 폰 홈 화면에 앱 아이콘 추가",
      "사용자 피드백 루프와 점진적 개선",
    ],
    relatedSkills: [
      "install-and-first-run",
      "permissions-and-safety",
      "one-slice-loop",
      "plan-mode-and-context",
      "prompt-writing",
      "git-workflow",
      "rules-file-deep-dive",
      "error-debugging",
    ],
  },
];

export function getCourse(slug: string) {
  return COURSES.find((c) => c.slug === slug);
}
